### ISSUE TITLE
Findroid is bypassing my system sound settings

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jarnedemeulemeester/findroid#127]
Hi,

That's the first time I see this on my phone (Redmi Note 8T on crDroid 8.6, Android 12.1). **Findroid is completely bypassing my system sound settings and sound outputs via the loudspeaker everytime, at maximum volume.** 

Even if my system volume is limited or set to mute, even if headphones are plugged in, even if bluetooth speakers are connected. Findroid always uses internal loudspeaker, and doesn't appear in the sound mixer. 

I don't even understand how it is possible, I didn't know apps could technically take over the system sound mixer but apparently Findroid does. And I can't find how to make it behave like a normal app with sound.

I tried reinstalling the app, obviously. Searched a lot in my sound settings, both system and in-app...  Nothing seem to be related.
Findroid is the only app doing that.

Could anyone help me understand what is happening and what could be causing this ? How could I be the only one with this issue ?

Thanks in advance for any answer,
Have a good day

**Comment by OctoNezd** [comment]
I am having same issue on POCO X3 NFC. It seems to be specific to video files for me - they blast on max vol even outside findroid. And it happens only with surround audio. It seems that is ROM-side bug because according to one of testers for ArrowOS on my device the issue is fixed on builds that are sent to testers.

**Comment by OctoNezd** [comment]
No idea sadly, the fixes didnt hit public yet and I dont see anything in gerrit that screams fix

**Comment by jarnedemeulemeester** [comment]
I am closing this as it seems like this is a ROM-side bug.

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I tried Findroid again. Even on the latest releases of crdroid, the bug is still there. The sound still is bypassing system volume and outputs to the max. It probably happens with other custom roms.

To anyone having this issue, I found a solution
![Screenshot_20230609-002141_Findroid_1](https://github.com/jarnedemeulemeester/findroid/assets/64923542/4b62c64e-e39b-4b69-9eea-1f992f2700c7)
The solution is to switch player to MPV, and use opensles as your audio output. Audio should now work correctly.
